
#ifndef OCTETOS_CORE_DFA_SEMVER_V3_HH
#define OCTETOS_CORE_DFA_SEMVER_V3_HH

#include "lexer.hh"

namespace oct::core::v3::lc
{


/*
static const A::Transition regs[][MAX_SIMBOLS] = {
	//0
	{
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//tab
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},	
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//' '
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//#
		{Indicator::reject,0,tokens::none},//$
		{Indicator::reject,0,tokens::none},//%
		{Indicator::reject,0,tokens::none},//&
		{Indicator::reject,0,tokens::none},//'
		{Indicator::reject,0,tokens::none},//(
		{Indicator::reject,0,tokens::none},//)
		{Indicator::reject,0,tokens::none},//+
		{Indicator::reject,0,tokens::none},//,
		{Indicator::reject,0,tokens::none},//-
		{Indicator::reject,0,tokens::none},//.
		{Indicator::reject,0,tokens::none},// /
		{Indicator::reject,0,tokens::none},//0
		{Indicator::reject,0,tokens::none},//1
		{Indicator::reject,0,tokens::none},//2
		{Indicator::reject,0,tokens::none},//3
		{Indicator::reject,0,tokens::none},//4
		{Indicator::reject,0,tokens::none},//5
		{Indicator::reject,0,tokens::none},//6
		{Indicator::reject,0,tokens::none},//7
		{Indicator::reject,0,tokens::none},//8
		{Indicator::reject,0,tokens::none},//9
		{Indicator::reject,0,tokens::none},//:
		{Indicator::reject,0,tokens::none},//;
		{Indicator::reject,0,tokens::none},//<
		{Indicator::reject,0,tokens::none},//=
		{Indicator::reject,0,tokens::none},//>
		{Indicator::reject,0,tokens::none},//?
		{Indicator::reject,0,tokens::none},//@
		{Indicator::reject,0,tokens::none},//A
		{Indicator::reject,0,tokens::none},//B
		{Indicator::reject,0,tokens::none},//C
		{Indicator::reject,0,tokens::none},//D
		{Indicator::reject,0,tokens::none},//E
		{Indicator::reject,0,tokens::none},//F
		{Indicator::reject,0,tokens::none},//G
		{Indicator::reject,0,tokens::none},//H
		{Indicator::reject,0,tokens::none},//I
		{Indicator::reject,0,tokens::none},//J
		{Indicator::reject,0,tokens::none},//K
		{Indicator::reject,0,tokens::none},//L
		{Indicator::reject,0,tokens::none},//M
		{Indicator::reject,0,tokens::none},//N
		{Indicator::reject,0,tokens::none},//O
		{Indicator::reject,0,tokens::none},//P
		{Indicator::reject,0,tokens::none},//Q
		{Indicator::reject,0,tokens::none},//R
		{Indicator::reject,0,tokens::none},//S
		{Indicator::reject,0,tokens::none},//T
		{Indicator::reject,0,tokens::none},//U
		{Indicator::reject,0,tokens::none},//V
		{Indicator::reject,0,tokens::none},//W
		{Indicator::reject,0,tokens::none},//X
		{Indicator::reject,0,tokens::none},//Y
		{Indicator::reject,0,tokens::none},//Z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//_
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//a
		{Indicator::reject,0,tokens::none},//b
		{Indicator::reject,0,tokens::none},//c
		{Indicator::reject,0,tokens::none},//d
		{Indicator::reject,0,tokens::none},//e
		{Indicator::reject,0,tokens::none},//f
		{Indicator::reject,0,tokens::none},//g
		{Indicator::reject,0,tokens::none},//h
		{Indicator::reject,0,tokens::none},//i
		{Indicator::reject,0,tokens::none},//j
		{Indicator::reject,0,tokens::none},//k
		{Indicator::reject,0,tokens::none},//l
		{Indicator::reject,0,tokens::none},//m
		{Indicator::reject,0,tokens::none},//n
		{Indicator::reject,0,tokens::none},//o
		{Indicator::reject,0,tokens::none},//p
		{Indicator::reject,0,tokens::none},//q
		{Indicator::reject,0,tokens::none},//r
		{Indicator::reject,0,tokens::none},//s
		{Indicator::reject,0,tokens::none},//t
		{Indicator::reject,0,tokens::none},//u
		{Indicator::reject,0,tokens::none},//v
		{Indicator::reject,0,tokens::none},//w
		{Indicator::reject,0,tokens::none},//x
		{Indicator::reject,0,tokens::none},//y
		{Indicator::reject,0,tokens::none},//z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
	},
};
*/


static const A<char,tokens,Status>::Transition semver_tt[][MAX_SIMBOLS] = {
	//0
	{
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//tab
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},	
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//' '
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//+
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//-
		{Indicator::reject,0,tokens::none},//.
		{Indicator::reject,0,tokens::none},
		{Indicator::acceptable,1,tokens::number},//0
		{Indicator::acceptable,1,tokens::number},//1
		{Indicator::acceptable,1,tokens::number},//2
		{Indicator::acceptable,1,tokens::number},//3
		{Indicator::acceptable,1,tokens::number},//4
		{Indicator::acceptable,1,tokens::number},//5
		{Indicator::acceptable,1,tokens::number},//6
		{Indicator::acceptable,1,tokens::number},//7
		{Indicator::acceptable,1,tokens::number},//8
		{Indicator::acceptable,1,tokens::number},//9
		{Indicator::reject,0,tokens::none},//:
		{Indicator::reject,0,tokens::none},//;
		{Indicator::reject,0,tokens::none},//<
		{Indicator::reject,0,tokens::none},//=
		{Indicator::reject,0,tokens::none},//>
		{Indicator::reject,0,tokens::none},//?
		{Indicator::reject,0,tokens::none},//@
		{Indicator::reject,0,tokens::none},//A
		{Indicator::reject,0,tokens::none},//B
		{Indicator::reject,0,tokens::none},//C
		{Indicator::reject,0,tokens::none},//D
		{Indicator::reject,0,tokens::none},//E
		{Indicator::reject,0,tokens::none},//F
		{Indicator::reject,0,tokens::none},//G
		{Indicator::reject,0,tokens::none},//H
		{Indicator::reject,0,tokens::none},//I
		{Indicator::reject,0,tokens::none},//J
		{Indicator::reject,0,tokens::none},//K
		{Indicator::reject,0,tokens::none},//L
		{Indicator::reject,0,tokens::none},//M
		{Indicator::reject,0,tokens::none},//N
		{Indicator::reject,0,tokens::none},//O
		{Indicator::reject,0,tokens::none},//P
		{Indicator::reject,0,tokens::none},//Q
		{Indicator::reject,0,tokens::none},//R
		{Indicator::reject,0,tokens::none},//S
		{Indicator::reject,0,tokens::none},//T
		{Indicator::reject,0,tokens::none},//U
		{Indicator::reject,0,tokens::none},//V
		{Indicator::reject,0,tokens::none},//W
		{Indicator::reject,0,tokens::none},//X
		{Indicator::reject,0,tokens::none},//Y
		{Indicator::reject,0,tokens::none},//Z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//_
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//a
		{Indicator::reject,0,tokens::none},//b
		{Indicator::reject,0,tokens::none},//c
		{Indicator::reject,0,tokens::none},//d
		{Indicator::reject,0,tokens::none},//e
		{Indicator::reject,0,tokens::none},//f
		{Indicator::reject,0,tokens::none},//g
		{Indicator::reject,0,tokens::none},//h
		{Indicator::reject,0,tokens::none},//i
		{Indicator::reject,0,tokens::none},//j
		{Indicator::reject,0,tokens::none},//k
		{Indicator::reject,0,tokens::none},//l
		{Indicator::reject,0,tokens::none},//m
		{Indicator::reject,0,tokens::none},//n
		{Indicator::reject,0,tokens::none},//o
		{Indicator::reject,0,tokens::none},//p
		{Indicator::reject,0,tokens::none},//q
		{Indicator::reject,0,tokens::none},//r
		{Indicator::reject,0,tokens::none},//s
		{Indicator::reject,0,tokens::none},//t
		{Indicator::reject,0,tokens::none},//u
		{Indicator::reject,0,tokens::none},//v
		{Indicator::reject,0,tokens::none},//w
		{Indicator::reject,0,tokens::none},//x
		{Indicator::reject,0,tokens::none},//y
		{Indicator::reject,0,tokens::none},//z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
	},
	//1
	{
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//tab
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},	
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//' '
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::prefix,0,tokens::none},//+
		{Indicator::reject,0,tokens::none},
		{Indicator::prefix,0,tokens::none},//-
		{Indicator::prefix,0,tokens::none},//.
		{Indicator::reject,0,tokens::none},// /
		{Indicator::acceptable,1,tokens::number},//0
		{Indicator::acceptable,1,tokens::number},//1
		{Indicator::acceptable,1,tokens::number},//2
		{Indicator::acceptable,1,tokens::number},//3
		{Indicator::acceptable,1,tokens::number},//4
		{Indicator::acceptable,1,tokens::number},//5
		{Indicator::acceptable,1,tokens::number},//6
		{Indicator::acceptable,1,tokens::number},//7
		{Indicator::acceptable,1,tokens::number},//8
		{Indicator::acceptable,1,tokens::number},//9
		{Indicator::reject,0,tokens::none},//:
		{Indicator::reject,0,tokens::none},//;
		{Indicator::reject,0,tokens::none},//<
		{Indicator::reject,0,tokens::none},//=
		{Indicator::reject,0,tokens::none},//>
		{Indicator::reject,0,tokens::none},//?
		{Indicator::reject,0,tokens::none},//@
		{Indicator::reject,0,tokens::none},//A
		{Indicator::reject,0,tokens::none},//B
		{Indicator::reject,0,tokens::none},//C
		{Indicator::reject,0,tokens::none},//D
		{Indicator::reject,0,tokens::none},//E
		{Indicator::reject,0,tokens::none},//F
		{Indicator::reject,0,tokens::none},//G
		{Indicator::reject,0,tokens::none},//H
		{Indicator::reject,0,tokens::none},//I
		{Indicator::reject,0,tokens::none},//J
		{Indicator::reject,0,tokens::none},//K
		{Indicator::reject,0,tokens::none},//L
		{Indicator::reject,0,tokens::none},//M
		{Indicator::reject,0,tokens::none},//N
		{Indicator::reject,0,tokens::none},//O
		{Indicator::reject,0,tokens::none},//P
		{Indicator::reject,0,tokens::none},//Q
		{Indicator::reject,0,tokens::none},//R
		{Indicator::reject,0,tokens::none},//S
		{Indicator::reject,0,tokens::none},//T
		{Indicator::reject,0,tokens::none},//U
		{Indicator::reject,0,tokens::none},//V
		{Indicator::reject,0,tokens::none},//W
		{Indicator::reject,0,tokens::none},//X
		{Indicator::reject,0,tokens::none},//Y
		{Indicator::reject,0,tokens::none},//Z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//_
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},//a
		{Indicator::reject,0,tokens::none},//b
		{Indicator::reject,0,tokens::none},//c
		{Indicator::reject,0,tokens::none},//d
		{Indicator::reject,0,tokens::none},//e
		{Indicator::reject,0,tokens::none},//f
		{Indicator::reject,0,tokens::none},//g
		{Indicator::reject,0,tokens::none},//h
		{Indicator::reject,0,tokens::none},//i
		{Indicator::reject,0,tokens::none},//j
		{Indicator::reject,0,tokens::none},//k
		{Indicator::reject,0,tokens::none},//l
		{Indicator::reject,0,tokens::none},//m
		{Indicator::reject,0,tokens::none},//n
		{Indicator::reject,0,tokens::none},//o
		{Indicator::reject,0,tokens::none},//p
		{Indicator::reject,0,tokens::none},//q
		{Indicator::reject,0,tokens::none},//r
		{Indicator::reject,0,tokens::none},//s
		{Indicator::reject,0,tokens::none},//t
		{Indicator::reject,0,tokens::none},//u
		{Indicator::reject,0,tokens::none},//v
		{Indicator::reject,0,tokens::none},//w
		{Indicator::reject,0,tokens::none},//x
		{Indicator::reject,0,tokens::none},//y
		{Indicator::reject,0,tokens::none},//z
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
		{Indicator::reject,0,tokens::none},
	},
};




}

#endif